name: Test
on:
  push:
    branches:
      - master
      - develop
    paths:
      - .github/workflows/*.yml
      - src/**.[jt]sx?
  pull_request:
    branches:
      - '*'
    paths:
      - .github/workflows/*.yml
      - src/**.[jt]sx?

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "13.x"

      - name: Install dependencies
        run: |
          yarn install

      - name: Test
        run: |
          yarn test
